### PR TITLE
expand shell var for .clang; set clang cwd to the location of .clang;

### PR DESCRIPTION
**Pull request by fcying**
expand shell var for .clang

set clang cwd to the location of .clang for #5

### CODE REVIEW

**Comment by Shougo** [comment]
Please use single quote instead.

**Comment by Shougo** [comment]
Why `Source.run_dir` is needed?
Please describe it for me.

**Comment by fcying** [comment]
Source.run_dir  default value is `context['cwd']`, if find `.clang`, set `dirname(clang_file)`.
It will changes the clang working dir to cwd before subprocess executing the child.
and then, the include path which set in .clang file will relative to the .clang file, not relative to work dir.

Single quotes have been modified

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
